sudo: required
services:
  - docker

before_install:
  - docker build -t iouoi/react-test -f ./client/Dockerfile.dev ./client

script:  # this is the primary test-running section. If any script here exit with a status other than 0, Travis CI assumes our build failed
  - docker run iouoi/react-test npm test -- --coverage

after_success:  # add in config that'll build production version of all our projects and push them off to docker hub
  - docker build -t iouoi/multi-client ./client
  - docker build -t iouoi/multi-nginx ./nginx
  - docker build -t iouoi/multi-server ./server
  - docker build -t iouoi/multi-worker ./worker
  # Now, take these images and push them to docker hub 
  # (first need to log in to docker cli)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # retrieve your password from env variable, and emit that over stdin as input to the next command ('docker login' command), while telling it that it can expect to receive password over stdin.

  - docker push iouoi/multi-client
  - docker push iouoi/multi-nginx
  - docker push iouoi/multi-server
  - docker push iouoi/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-492606371812
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY


